### PR TITLE
Create french translation

### PR DESCRIPTION
**Pull request by alKODIque**
Create french translation

### CODE REVIEW

**Comment by alKODIque** [comment]
@jurialmunkey 
Hi, 
I was wondering if there was a problem with my translation. Several french users ask me for the link to my version but I hate giving access to addons for which there is an official repository
Thank you very much, and please tell me if I need to modify anything for getting it merged in your repository 😉

**Comment by jurialmunkey** [comment]
Hi. Sorry, no there's no issue with the translation -- I've just been busy with work and getting Eminence back on the official repo for matrix. Plus I've been slowly working on a "Arctic Horizon 2" which is being written from the ground up (not released yet) so I haven't touched this repo in a few months.

I'll merge now.

**Comment by alKODIque** [comment]
Thanks a lot for merging,, 

I'm very glad to ear that you are working on AH2!! Wow!!
I Love this skin, (and I'm not the only one 😉)

Thank you for all the hard work you are doing for us ❤

**Comment by drinfernoo** [comment]
@jurialmunkey Can we get a version bump?

**Comment by jurialmunkey** [comment]
Done.

**Pull request merged**
