### PR TITLE
Added dutch translations.

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Impressive! 👍

**Comment by jurialmunkey** [comment]
Amazing! Thank you! 😄

**Comment by drinfernoo** [comment]
@nazegnl, when you make these, will you bump the patch version? That way merging will create an actual update 😉

**Comment by jurialmunkey** [comment]
> 
> 
> @nazegnl, when you make these, will you bump the patch version? That way merging will create an actual update 😉

Bumped! 😉

**Pull request merged**
