### PR TITLE
:art: - Add "Songs" to default search menu as well

### PR DESCRIPTION
**Pull request by drinfernoo**
https://github.com/jurialmunkey/skin.arctic.horizon/pull/188#pullrequestreview-422318777

### CODE REVIEW

**Comment by jurialmunkey** [comment]
I think you probably need to also set a default aspect for it in overrides to be square as poster doesn't make sense for songs.

**Comment by jurialmunkey** [comment]
BTW, aspect for search defaults are set here:
https://github.com/jurialmunkey/skin.arctic.horizon/blob/master/shortcuts/overrides.xml#L178-L189

**Comment by drinfernoo** [comment]
Done :+1:

**Comment by jurialmunkey** [comment]
👍

**Pull request merged**
