### PR TITLE
Fix Information Screen Buttons

### PR DESCRIPTION
**Pull request by WatchThemFall**
Fixes Information screen buttons so you can click on them, and adds an extra line to the info screen's description.

Probably not the best way since you have to do it in 2 locations, but if you change the left, top, height properties in Defs_ButtonList it breaks them in the widgets.

### CODE REVIEW

**Comment by WatchThemFall** [comment]
Probably not the best way since you have to do it in 2 locations, but if you change the left, top, height properties in Defs_ButtonList it breaks them in the widgets.

**Comment by jurialmunkey** [comment]
Hey, thanks for submitting this PR. Unfortunately it isn't really suitable because it messes with the alignment in the grouplist. If you see in the screenshot below, the buttons should align between the two green horizontal lines and the cast list show bottom align with the strong red line at the bottom of the screen (i.e. the bottom of the cast list should align with the bottom of the poster).
Honeyview_screenshot707

IT does give me some idea of how this issue might be fixed though! Still not sure why it won't work inside the group it is currently in...

**Comment by WatchThemFall** [comment]
Sorry. I really didn't know what I was doing I just wanted to get it to work with the mouse. Why do the buttons need to be in the green lines, though? I moved them down a little bit so 3 lines of the summary could fit. And I tried to line it up so the green highlight the portrait lined up with the poster so it didn't scroll down when you were on the cast. (but I did just do it by eye it's probably a little off)

**Comment by jurialmunkey** [comment]
Because those are the design specifications of the skin. The baseline of the buttons should be 40 px above the centerline and the baseline of the cast should align with the baseline of the poster.

**Comment by jurialmunkey** [comment]
Anyway, I think I've managed to fix it now. Thanks again for the initial PR as it was really helpful for figuring out a way to fix this bug (I'm still confused about what was preventing it from working originally - but at least it is fixed now!)

---
Relevant Commit: https://github.com/jurialmunkey/skin.arctic.horizon/commit/d7e4357857826f817a13e711358698fddf1c51a9

**Pull request closed without merging**
