### PR TITLE
:pushpin: - Update xbmcgui to 0.5.15

### PR DESCRIPTION
**Pull request by drinfernoo**
I'm not able to request  that this be pulled to a new branch, but I would recommend simply cherrypicking this commit into a new `matrix` branch, on your end.

### CODE REVIEW

**Comment by drinfernoo** [comment]
@jurialmunkey, I believe similar changes need to be made to make AZ2 work as well, but will also need to have certain versions of dependencies updated as well

**Comment by jurialmunkey** [comment]
I typically don't start updating skins for a new skinning engine version until there's an RC. There's no real breaking changes in Matrix skinning engine so far but I don't want to give a false indication that I've switched to Matrix when I haven't yet.

I've tried in the past of maintaining two separate branches for skins and cherry-picking in commits as needed but it really isn't feasible long term - it's just way too difficult to keep track of what works in each version and it ends up becoming a case of having to code every new feature twice. 

Typically I'll keep two branches whilst the RC is out, then once there's a finalised release I stop working on the old version altogether and only work on the new one.

**Comment by drinfernoo** [comment]
Bummer... just makes it impossible to install AH from the repo (even the Matrix one) 😫

**Comment by drinfernoo** [comment]
For my own sanity, but also for your information, I'm going to pause updating Arctic Horizon on the Matrix branch of the repository for the time being. Unless you are averse to this, I'm going to simply update the plugins until AH/Kodi have reached a point where they're stable enough to merge this.

**Comment by jurialmunkey** [comment]
FYI there is now a Matrix version in the Matrix branch and should be ready to be pulled into the Matrix repo.

**Pull request closed without merging**
